<?php

/**
 * @file
 * Contains cron_queue_viewer.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cron_queue_viewer_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cron_queue_viewer module.
    case 'help.page.cron_queue_viewer':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module to view cron tasks and queues') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function cron_queue_viewer_theme() {
  return [
    'cron_queue_viewer' => [
      'render element' => 'children',
    ],
  ];
}
